# This rule is not used by the project kubebuilder-crd itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to example.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
  name: statusalert-viewer-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - statusalerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - statusalerts/status
  verbs:
  - get
